#!/usr/bin/env python3

import sys
import math
import re
import subprocess
import shutil
import json
from pathlib import Path

# Displace the hotspot to the right and down by 1/100th of a pixel, then
# floor. So if by some float error the hotspot is at 4.995, it will be
# displaced to 5.005, then floored to 5. This is to prevent the hotspot
# from potential off-by-one errors when the cursor is scaled.
HOTSPOT_DISPLACE = 1

if len(sys.argv) <= 4:
    print("Usage: " + sys.argv[0] + " <scalable_cursors_dir> <pixmap dir> <xcursor output dir> <scales>")
    sys.exit(1)

scalable_cursors_dir = Path(sys.argv[1])
pixmap_dir = Path(sys.argv[2])
xcursor_output_dir = Path(sys.argv[3])
scales = [int(i) for i in sys.argv[4:]]

cursor_dirs = [d for d in scalable_cursors_dir.iterdir() if d.is_dir()]
processed_svgs = set()
for d in cursor_dirs:
    # Get the primary SVG file
    svg_files = list(d.glob("*.svg"))
    if len(svg_files) == 0:
        raise FileNotFoundError("Couldn't find an SVG for the cursor.")
    elif len(svg_files) > 1:
        svg_files.sort()
    svg = svg_files[0]

    if svg in processed_svgs:
        continue
    processed_svgs.add(svg)

    basename = svg.stem
    basename = re.sub(r"-[0-9_]*$", "", basename)
    print(f"   {basename}")

    # Get the configuration file and fetch some essential properties
    config_file = list(d.glob("metadata.json"))[0]
    nominal_size = None
    hotspot_x = None
    hotspot_y = None
    with config_file.open() as f:
        # Should ideally be a list, with how KDE Plasma specifies their configuration
        j = json.load(f)
        if len(j) == 0:
            raise IndexError("Missing Cursor Metadata")
        conf = j[0]
        nominal_size = conf["nominal_size"]
        hotspot_x = conf["hotspot_x"]
        hotspot_y = conf["hotspot_y"]
    
    # Generate xcursor
    xcursor_config_path = pixmap_dir / "config" / f"{basename}.config"
    with open(xcursor_config_path, "w") as config:
        for scale in scales:
            actual_size = math.floor(nominal_size * scale / 100)
            hx = max(0, math.floor((hotspot_x * scale + HOTSPOT_DISPLACE) / 100))
            hy = max(0, math.floor((hotspot_y * scale + HOTSPOT_DISPLACE) / 100))
            config.write(f"{actual_size} {hx} {hy} x{scale}/{basename}.png\n")
            # TODO: Add animation support
            # if len(frames) == 0:
            #     print(f"{size} {hotspot_x} {hotspot_y} x{scale}/{basename}.png", file=config)
            # else:
            #     for i in frames:
            #         t = i.stem
            #         print(f"{size} {hotspot_x} {hotspot_y} x{scale}/{t}.png {delay}", file=config)
            
    subprocess.run(["xcursorgen", "-p", pixmap_dir, xcursor_config_path, xcursor_output_dir / basename], check=True)